CREATE TABLE regions
(
region_id NUMBER --GENERATED BY DEFAULT AS IDENTITY
 PRIMARY KEY,
region_name VARCHAR2(50) NOT NULL
);

--------------
CREATE TABLE countries
(
  country_id CHAR(2) PRIMARY KEY,
  country_name VARCHAR2(40) NOT NULL,
  region_id NUMBER,
  CONSTRAINT fk_countries_regions FOREIGN KEY(region_id)
  REFERENCES regions(region_id)
  ON DELETE CASCADE
  );
  
  ---------------
CREATE TABLE locations
(
location_id NUMBER PRIMARY KEY,
address VARCHAR2(225) NOT NULL,
postal_code VARCHAR(20),
city VARCHAR2(20),
state VARCHAR2(20),
country_id CHAR(2),
CONSTRAINT fk_locations_countries
  FOREIGN KEY(country_id)
  REFERENCES countries(country_id)
  ON DELETE CASCADE
  );
  
------

CREATE TABLE warehouses
(
warehouse_id NUMBER PRIMARY KEY,
warehouse_name VARCHAR2(50),
location_id NUMBER(12,0),
CONSTRAINT fk_warehouse_locations
  FOREIGN KEY(location_id)
  REFERENCES locations(location_id)
  ON DELETE CASCADE
);

---------
CREATE TABLE employees
(
employee_id NUMBER PRIMARY KEY,
first_name VARCHAR2(15) NOT NULL,
last_name VARCHAR2(15) NOT NULL,
email VARCHAR2(25) NOT NULL,
phone VARCHAR2(10) NOT NULL,
hire_date DATE NOT NULL,
manager_id NUMBER(12,0) ,
job_title VARCHAR2(15) NOT NULL,
CONSTRAINT fk_employees_manager
  FOREIGN KEY(manager_id)
  REFERENCES employees(employee_id)
  ON DELETE CASCADE
  );
-----------
CREATE TABLE product_categories
(
category_id NUMBER PRIMARY key,
category_name VARCHAR2(30) NOT NULL
);
----------
CREATE TABLE products
(
product_id NUMBER PRIMARY KEY,
product_name VARCHAR2(25) NOT NULL,
description VARCHAR2(80),
standard_cost NUMBER(9,2),
list_price NUMBER(9,2),
category_id NUMBER NOT NULL,
CONSTRAINT fk_product_categories
  FOREIGN KEY(category_id)
  REFERENCES product_categories(category_id)
  ON DELETE CASCADE
  );
-------------------
CREATE TABLE customers
(
customer_id NUMBER PRIMARY KEY,
name VARCHAR2(20) NOT NULL,
address VARCHAR2(80) ,
website VARCHAR2(80),
credit_limit NUMBER(8,2)
);
---------------
CREATE TABLE contacts
(
contact_id NUMBER PRIMARY KEY,
first_name VARCHAR2(20) NOT NULL,
last_name VARCHAR2(20) NOT NULL,
email VARCHAR2(30) NOT NULL,
phone VARCHAR2(10),
customer_id NUMBER,
CONSTRAINT fk_contacts_customers
FOREIGN KEY(customer_id)
REFERENCES customers(customer_id)
ON DELETE CASCADE
);
------------------
CREATE TABLE orders
(
order_id NUMBER PRIMARY KEY,
customer_id NUMBER(6,0) NOT NULL,
status VARCHAR2(20) NOT NULL,
salesman_id NUMBER(6,0),
order_date DATE NOT NULL,
CONSTRAINT fk_orders_customers
FOREIGN KEY(customer_id)
REFERENCES customers(customer_id)
ON DELETE CASCADE,
CONSTRAINT fk_orders_employees
FOREIGN KEY(salesman_id)
REFERENCES employees(employee_id)
ON DELETE SET NULL
);
-----------

CREATE TABLE order_items
(
order_id NUMBER(12,0),
item_id NUMBER(12,0),
product_id NUMBER(12,0) NOT NULL,
quantity NUMBER(8,2) NOT NULL,
unit_price NUMBER(12,0) NOT NULL,
CONSTRAINT pk_order_items
PRIMARY KEY(order_id,item_id), 
CONSTRAINT fk_orders_items_products
FOREIGN KEY(product_id)
REFERENCES products(product_id)
ON DELETE CASCADE,
CONSTRAINT fk_orders_items_orders
FOREIGN KEY(order_id)
REFERENCES orders(order_id)
ON DELETE CASCADE
);
-------------------

CREATE TABLE inventories
(
product_id NUMBER(12,0),
warehouse_id NUMBER(12,0),
quantity NUMBER(8,2) NOT NULL,
CONSTRAINT pk_inventories
PRIMARY KEY(product_id,warehouse_id), 
CONSTRAINT fk_inventories_products
FOREIGN KEY(product_id)
REFERENCES products(product_id)
ON DELETE CASCADE,
CONSTRAINT fk_inventories_warehouses
FOREIGN KEY(warehouse_id)
REFERENCES warehouses(warehouse_id)
ON DELETE CASCADE
);
------
--autonomous transaction for logging

CREATE TABLE app_logs(
log_id NUMBER PRIMARY KEY,
  log_ts TIMESTAMP,
  log_level VARCHAR2(10),
  message VARCHAR2(4000)
);

CREATE SEQUENCE seq_log START WITH 1 NOCACHE;
